### ISSUE TITLE
Problem with connection to the socket name space

### ISSUE THREAD

**Issue by imanis** [braitsch/sub.socket.io#1]
Hi, 
I am trying to test your code.
After installing every thing, putting hosts, and running node app, i get the web interface but i can not send or get message.
In the console it shows that it can not connect to socket io namesapces.
I have tried many things like checking ports, hosts, updating socketio to 1.x version, but with no success.

the log say:
GET http://localhost/socket.io/?EIO=3&transport=polling&t=1437734559729-0 net::ERR_CONNECTION_REFUSED

**Comment by braitsch** [comment]
I just updated the project to express v4.13.1 & socket.io v1.3.6. There were a bunch of issues related to more recent versions of Node that should now be resolved.
